apiVersion: apps/v1
kind : Deployment
metadata:
  name: web-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: pedrofraca/web-app:1.2
        ports:
        - name: web
          containerPort: 80
---
apiVersion : v1
kind : Service
metadata:
  name: web-app-service
spec:
  ports:
  - port: 80
    nodePort: 31003
    targetPort: web
    protocol: TCP
  selector:
    app: web-app
  type: NodePort
